In [1]:
import pandas as pd
import numpy as np

In [2]:
procurement = pd.read_csv(
    "../data/cleaned/cleaned_procurement.csv"
)

purchases = pd.read_csv(
    "../data/cleaned/cleaned_purchases.csv"
)

In [3]:
procurement.head()

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price,Negotiated_Price,Defective_Units,Compliance,Delivery_Missing,Delivery_Delay_Days,Savings_Per_Unit,Total_Savings,Defect_Rate
0,PO-00001,ALPHA_INC,2023-10-17,2023-10-25,OFFICE SUPPLIES,CANCELLED,1176,20.13,17.81,0.0,YES,False,8.0,2.32,2728.32,0.000000
1,PO-00002,DELTA_LOGISTICS,2022-04-25,2022-05-05,OFFICE SUPPLIES,DELIVERED,1509,39.32,37.34,235.0,YES,False,10.0,1.98,2987.82,0.155732
2,PO-00003,GAMMA_CO,2022-01-26,2022-02-15,MRO,DELIVERED,910,95.51,92.26,41.0,YES,False,20.0,3.25,2957.50,0.045055
3,PO-00004,BETA_SUPPLIES,2022-10-09,2022-10-28,PACKAGING,DELIVERED,1344,99.85,95.52,112.0,YES,False,19.0,4.33,5819.52,0.083333
4,PO-00005,DELTA_LOGISTICS,2022-09-08,2022-09-20,RAW MATERIALS,DELIVERED,1180,64.07,60.53,171.0,NO,False,12.0,3.54,4177.20,0.144915

In [4]:
purchases.head()

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification,Lead_Time_Days,Invoice_Processing_Days,Payment_Cycle_Days,Unit_Cost
0,69_MOUNTMEND_8412,69,8412,TEQUILA OCHO PLATA FRESNO,750ML,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1,12,2,43,35.71
1,30_CULCHETH_5255,30,5255,TGI FRIDAYS ULTIMTE MUDSLIDE,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1,10,6,45,9.35
2,34_PITMERDEN_5215,34,5215,TGI FRIDAYS LONG ISLAND ICED,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1,11,5,45,9.41
3,1_HARDERSFIELD_5255,1,5255,TGI FRIDAYS ULTIMTE MUDSLIDE,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1,10,6,45,9.35
4,76_DONCASTER_2034,76,2034,GLENDALOUGH DOUBLE BARREL,750ML,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1,9,7,38,21.32

In [5]:
top_suppliers = (
    purchases.groupby('VendorName')['Dollars']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

top_suppliers.head(10)

                   VendorName      Dollars
0    DIAGEO NORTH AMERICA INC  50959796.85
1       MARTIGNETTI COMPANIES  27861690.02
2     JIM BEAM BRANDS COMPANY  24203151.05
3           PERNOD RICARD USA  24124091.56
4             BACARDI USA INC  17624378.72
5    CONSTELLATION BRANDS INC  15573917.90
6           BROWN-FORMAN CORP  13529433.08
7  ULTRA BEVERAGE COMPANY LLP  13210613.93
8          E & J GALLO WINERY  12289608.09
9              M S WALKER INC  10935817.30

In [6]:
total_spend = purchases['Dollars'].sum()

top10_spend = top_suppliers.head(10)['Dollars'].sum()

top10_percentage = (top10_spend / total_spend) * 100

print("Total Spend:", round(total_spend, 2))
print("Top 10 Supplier Spend:", round(top10_spend, 2))
print("Top 10 Spend Percentage:", round(top10_percentage, 2), "%")

Total Spend: 321900765.53
Top 10 Supplier Spend: 210312498.5
Top 10 Spend Percentage: 65.33 %

In [7]:
supplier_leadtime = (
    purchases.groupby('VendorName')['Lead_Time_Days']
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

supplier_leadtime.head(10)

                      VendorName  Lead_Time_Days
0             FLAVOR ESSENCE INC       13.000000
1            LAUREATE IMPORTS CO       10.000000
2    AAPER ALCOHOL & CHEMICAL CO       10.000000
3  IRA GOLDMAN AND WILLIAMS, LLP        9.615385
4           BLACK COVE BEVERAGES        9.318182
5             VINEDREA WINES LLC        8.818182
6        WALPOLE MTN VIEW WINERY        8.527027
7         SILVER MOUNTAIN CIDERS        8.500000
8          STARK BREWING COMPANY        8.487805
9     ULTRA BEVERAGE COMPANY LLP        8.410477

In [8]:
supplier_risk = (
    purchases.groupby('VendorName')
    .agg({
        'Dollars': 'sum',
        'Lead_Time_Days': 'mean'
    })
    .reset_index()
)

supplier_risk = supplier_risk.sort_values(
    by=['Dollars', 'Lead_Time_Days'],
    ascending=[False, False]
)

supplier_risk.head(10)

                     VendorName      Dollars  Lead_Time_Days
28     DIAGEO NORTH AMERICA INC  50959796.85        7.549649
63        MARTIGNETTI COMPANIES  27861690.02        7.786131
50      JIM BEAM BRANDS COMPANY  24203151.05        7.512969
74            PERNOD RICARD USA  24124091.56        7.560950
8               BACARDI USA INC  17624378.72        7.700303
24     CONSTELLATION BRANDS INC  15573917.90        7.735626
14            BROWN-FORMAN CORP  13529433.08        7.547417
114  ULTRA BEVERAGE COMPANY LLP  13210613.93        8.410477
33           E & J GALLO WINERY  12289608.09        7.619708
59               M S WALKER INC  10935817.30        7.905499

In [9]:
category_savings = (
    procurement.groupby('Item_Category')['Total_Savings']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

category_savings

     Item_Category  Total_Savings
0              MRO      902312.31
1  OFFICE SUPPLIES      844096.16
2      ELECTRONICS      742876.23
3        PACKAGING      732744.52
4    RAW MATERIALS      709097.25

In [10]:
supplier_defects = (
    procurement.groupby('Supplier')['Defect_Rate']
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

supplier_defects

          Supplier  Defect_Rate
0  DELTA_LOGISTICS     0.108666
1    BETA_SUPPLIES     0.082723
2         GAMMA_CO     0.044975
3    EPSILON_GROUP     0.026063
4        ALPHA_INC     0.018905

In [11]:
category_defects = (
    procurement.groupby('Item_Category')['Defect_Rate']
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

category_defects

     Item_Category  Defect_Rate
0  OFFICE SUPPLIES     0.063922
1    RAW MATERIALS     0.062721
2      ELECTRONICS     0.058092
3              MRO     0.053427
4        PACKAGING     0.050525

In [12]:
supplier_payment_cycle = (
    purchases.groupby('VendorName')['Payment_Cycle_Days']
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

supplier_payment_cycle.head(10)

                    VendorName  Payment_Cycle_Days
0  AAPER ALCOHOL & CHEMICAL CO           44.000000
1             LOYAL DOG WINERY           42.100000
2          LAUREATE IMPORTS CO           41.000000
3  GILMANTON WINERY & VINEYARD           40.348837
4         ALISA CARR BEVERAGES           39.634921
5              R.P.IMPORTS INC           39.547945
6           FLAVOR ESSENCE INC           38.000000
7           VINEDREA WINES LLC           37.757576
8    AMERICAN SPIRITS EXCHANGE           37.750000
9                     UNCORKED           37.687500

In [13]:
supplier_unit_cost = (
    purchases.groupby('VendorName')['Unit_Cost']
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

supplier_unit_cost.head(10)

                    VendorName   Unit_Cost
0  AAPER ALCOHOL & CHEMICAL CO  105.070000
1         ALISA CARR BEVERAGES   98.810317
2              R.P.IMPORTS INC   42.200411
3           ALTAMAR BRANDS LLC   35.272807
4           EDRINGTON AMERICAS   33.597711
5          VINEYARD BRANDS LLC   31.288261
6        CALEDONIA SPIRITS INC   31.119833
7       REMY COINTREAU USA INC   30.568377
8        MOET HENNESSY USA INC   29.689921
9             MARSALLE COMPANY   27.508036

In [14]:
purchases['PODate'] = pd.to_datetime(purchases['PODate'])

monthly_spend = (
    purchases.groupby(purchases['PODate'].dt.to_period('M'))['Dollars']
    .sum()
    .reset_index()
)

monthly_spend['PODate'] = monthly_spend['PODate'].astype(str)

monthly_spend

     PODate      Dollars
0   2023-12   6950117.22
1   2024-01  19138815.42
2   2024-02  20147364.53
3   2024-03  20252968.80
4   2024-04  21798729.53
5   2024-05  28693060.33
6   2024-06  29699192.07
7   2024-07  32193842.50
8   2024-08  30747883.70
9   2024-09  26840919.81
10  2024-10  31836531.74
11  2024-11  27252267.02
12  2024-12  26349072.86

In [16]:
category_spend = (
    procurement.groupby('Item_Category')[['Negotiated_Price', 'Quantity']]
    .apply(lambda x: (x['Negotiated_Price'] * x['Quantity']).sum())
    .sort_values(ascending=False)
    .reset_index(name='Total_Spend')
)

category_spend

     Item_Category  Total_Spend
0              MRO  10126608.86
1  OFFICE SUPPLIES  10007583.03
2      ELECTRONICS   8642550.60
3    RAW MATERIALS   8471241.42
4        PACKAGING   8125712.48

In [17]:
supplier_spend = (
    purchases.groupby('VendorName')['Dollars']
    .sum()
    .reset_index(name='Total_Spend')
)

supplier_lead = (
    purchases.groupby('VendorName')['Lead_Time_Days']
    .mean()
    .reset_index(name='Avg_Lead_Time')
)

supplier_defect = (
    procurement.groupby('Supplier')['Defect_Rate']
    .mean()
    .reset_index(name='Avg_Defect_Rate')
)

# standardize names for merge
supplier_defect['Supplier'] = supplier_defect['Supplier'].str.upper()
supplier_spend['VendorName'] = supplier_spend['VendorName'].str.upper()
supplier_lead['VendorName'] = supplier_lead['VendorName'].str.upper()

supplier_risk_final = (
    supplier_spend
    .merge(supplier_lead, on='VendorName', how='left')
    .merge(
        supplier_defect,
        left_on='VendorName',
        right_on='Supplier',
        how='left'
    )
)

supplier_risk_final = supplier_risk_final.sort_values(
    by=['Total_Spend', 'Avg_Lead_Time'],
    ascending=[False, False]
)

supplier_risk_final.head(10)

,VendorName,Total_Spend,Avg_Lead_Time,Supplier,Avg_Defect_Rate
28,DIAGEO NORTH AMERICA INC,50959796.85,7.549649,NaN,NaN
63,MARTIGNETTI COMPANIES,27861690.02,7.786131,NaN,NaN
50,JIM BEAM BRANDS COMPANY,24203151.05,7.512969,NaN,NaN
74,PERNOD RICARD USA,24124091.56,7.560950,NaN,NaN
8,BACARDI USA INC,17624378.72,7.700303,NaN,NaN
24,CONSTELLATION BRANDS INC,15573917.90,7.735626,NaN,NaN
14,BROWN-FORMAN CORP,13529433.08,7.547417,NaN,NaN
114,ULTRA BEVERAGE COMPANY LLP,13210613.93,8.410477,NaN,NaN
33,E & J GALLO WINERY,12289608.09,7.619708,NaN,NaN
59,M S WALKER INC,10935817.30,7.905499,NaN,NaN

In [18]:
monthly_spend['Previous_Month_Spend'] = monthly_spend['Dollars'].shift(1)

monthly_spend['Rolling_3Month_Avg'] = monthly_spend['Dollars'].rolling(3).mean()

monthly_spend['Spend_Growth_Rate'] = monthly_spend['Dollars'].pct_change()

In [19]:
monthly_spend_model = monthly_spend.dropna().reset_index(drop=True)

monthly_spend_model

,PODate,Dollars,Previous_Month_Spend,Rolling_3Month_Avg,Spend_Growth_Rate
0,2024-02,20147364.53,19138815.42,1.541210e+07,0.052697
1,2024-03,20252968.80,20147364.53,1.984638e+07,0.005242
2,2024-04,21798729.53,20252968.80,2.073302e+07,0.076323
3,2024-05,28693060.33,21798729.53,2.358159e+07,0.316272
4,2024-06,29699192.07,28693060.33,2.673033e+07,0.035065
5,2024-07,32193842.50,29699192.07,3.019536e+07,0.083997
6,2024-08,30747883.70,32193842.50,3.088031e+07,-0.044914
7,2024-09,26840919.81,30747883.70,2.992755e+07,-0.127064
8,2024-10,31836531.74,26840919.81,2.980845e+07,0.186119
9,2024-11,27252267.02,31836531.74,2.864324e+07,-0.143994
10,2024-12,26349072.86,27252267.02,2.847929e+07,-0.033142

In [20]:
monthly_spend_model.to_csv("../data/cleaned/monthly_spend_features.csv", index=False)